CREATE TABLE IF NOT EXISTS SYS_USER (
    MR_ID              TEXT PRIMARY KEY,
    MR_EMAIL           TEXT,
    MR_PASSWORD        TEXT,
    MR_NICKNAME        TEXT,
    MR_ADMIN           INTEGER DEFAULT 0,
    MR_STATUS          INTEGER DEFAULT 0,
    MR_CANCEL_TIME     TEXT,
    MR_REMIND_ENABLED  INTEGER DEFAULT 0,
    MR_REMIND_DAY      INTEGER,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_BOOK (
    MR_ID          TEXT PRIMARY KEY,
    MR_USER_ID     TEXT,
    MR_BOOK_NAME   TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_TEMPLATE_ITEM (
    MR_ID          TEXT PRIMARY KEY,
    MR_BOOK_ID     TEXT,
    MR_ITEM_NAME   TEXT,
    MR_ITEM_TYPE   INTEGER,
    MR_ICON        TEXT,
    MR_SORT        TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_MONTH_RECORD (
    MR_ID              TEXT PRIMARY KEY,
    MR_USER_ID         TEXT,
    MR_BOOK_ID         TEXT,
    MR_YEAR            INTEGER,
    MR_MONTH           INTEGER,
    MR_TOTAL_ASSET     TEXT,
    MR_TOTAL_LIABILITY TEXT,
    MR_NET_ASSET       TEXT,
    MR_MONTH_ON_MONTH  TEXT,
    MR_YEAR_ON_YEAR    TEXT,
    MR_NOTE            TEXT,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_MONTH_ITEM_RECORD (
    MR_ID               TEXT PRIMARY KEY,
    MR_YEAR             INTEGER,
    MR_MONTH            INTEGER,
    MR_BOOK_ID          TEXT,
    MR_TEMPLATE_ITEM_ID TEXT,
    MR_ITEM_VALUE       TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_CONFIG (
    MR_ID           TEXT PRIMARY KEY,
    MR_CONFIG_KEY   TEXT,
    MR_CONFIG_VALUE TEXT,
    MR_REMARK       TEXT,
    MR_CREATE_BY    TEXT,
    MR_CREATE_TIME  TEXT,
    MR_UPDATE_BY    TEXT,
    MR_UPDATE_TIME  TEXT,
    MR_IS_DELETED   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_EXPORT_TASK (
    MR_ID               TEXT PRIMARY KEY,
    MR_USER_ID          TEXT,
    MR_BOOK_ID          TEXT,
    MR_START_YEAR_MONTH TEXT,
    MR_END_YEAR_MONTH   TEXT,
    MR_STATUS           TEXT,
    MR_FILE_NAME        TEXT,
    MR_FAIL_REASON      TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_USER_OPERATE_LOG (
    MR_ID           TEXT PRIMARY KEY,
    MR_USER_ID      TEXT,
    MR_OPERATE_TYPE TEXT,
    MR_CONTENT      TEXT,
    MR_IP           TEXT,
    MR_CREATE_BY    TEXT,
    MR_CREATE_TIME  TEXT,
    MR_UPDATE_BY    TEXT,
    MR_UPDATE_TIME  TEXT,
    MR_IS_DELETED   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_BOOK (
    MR_ID          TEXT PRIMARY KEY,
    MR_USER_ID     TEXT,
    MR_BOOK_NAME   TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_MONTH_RECORD (
    MR_ID              TEXT PRIMARY KEY,
    MR_USER_ID         TEXT,
    MR_BOOK_ID         TEXT,
    MR_YEAR            INTEGER,
    MR_MONTH           INTEGER,
    MR_TOTAL_ASSET     TEXT,
    MR_TOTAL_LIABILITY TEXT,
    MR_NET_ASSET       TEXT,
    MR_MONTH_ON_MONTH  TEXT,
    MR_YEAR_ON_YEAR    TEXT,
    MR_NOTE            TEXT,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_MONTH_ITEM_RECORD (
    MR_ID               TEXT PRIMARY KEY,
    MR_YEAR             INTEGER,
    MR_MONTH            INTEGER,
    MR_BOOK_ID          TEXT,
    MR_TEMPLATE_ITEM_ID TEXT,
    MR_ITEM_VALUE       TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_TEMPLATE_ITEM (
    MR_ID          TEXT PRIMARY KEY,
    MR_BOOK_ID     TEXT,
    MR_ITEM_NAME   TEXT,
    MR_ITEM_TYPE   INTEGER,
    MR_ICON        TEXT,
    MR_SORT        TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);
