CREATE TABLE IF NOT EXISTS SYS_USER (
    MR_ID              TEXT PRIMARY KEY,
    MR_EMAIL           TEXT,
    MR_PASSWORD        TEXT,
    MR_NICKNAME        TEXT,
    MR_ADMIN           INTEGER DEFAULT 0,
    MR_STATUS          INTEGER DEFAULT 0,
    MR_CANCEL_TIME     TEXT,
    MR_REMIND_ENABLED  INTEGER DEFAULT 0,
    MR_REMIND_DAY      INTEGER,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_BOOK (
    MR_ID          TEXT PRIMARY KEY,
    MR_USER_ID     TEXT,
    MR_BOOK_NAME   TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_TEMPLATE_ITEM (
    MR_ID          TEXT PRIMARY KEY,
    MR_BOOK_ID     TEXT,
    MR_ITEM_NAME   TEXT,
    MR_ITEM_TYPE   INTEGER,
    MR_ICON        TEXT,
    MR_SORT        TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_MONTH_RECORD (
    MR_ID              TEXT PRIMARY KEY,
    MR_USER_ID         TEXT,
    MR_BOOK_ID         TEXT,
    MR_YEAR            INTEGER,
    MR_MONTH           INTEGER,
    MR_TOTAL_ASSET     TEXT,
    MR_TOTAL_LIABILITY TEXT,
    MR_NET_ASSET       TEXT,
    MR_MONTH_ON_MONTH  TEXT,
    MR_YEAR_ON_YEAR    TEXT,
    MR_NOTE            TEXT,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS FIN_MONTH_ITEM_RECORD (
    MR_ID               TEXT PRIMARY KEY,
    MR_YEAR             INTEGER,
    MR_MONTH            INTEGER,
    MR_BOOK_ID          TEXT,
    MR_TEMPLATE_ITEM_ID TEXT,
    MR_ITEM_VALUE       TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_CONFIG (
    MR_ID           TEXT PRIMARY KEY,
    MR_CONFIG_KEY   TEXT,
    MR_CONFIG_VALUE TEXT,
    MR_REMARK       TEXT,
    MR_CREATE_BY    TEXT,
    MR_CREATE_TIME  TEXT,
    MR_UPDATE_BY    TEXT,
    MR_UPDATE_TIME  TEXT,
    MR_IS_DELETED   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_EXPORT_TASK (
    MR_ID               TEXT PRIMARY KEY,
    MR_USER_ID          TEXT,
    MR_BOOK_ID          TEXT,
    MR_START_YEAR_MONTH TEXT,
    MR_END_YEAR_MONTH   TEXT,
    MR_STATUS           TEXT,
    MR_FILE_NAME        TEXT,
    MR_FAIL_REASON      TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_USER_OPERATE_LOG (
    MR_ID           TEXT PRIMARY KEY,
    MR_USER_ID      TEXT,
    MR_OPERATE_TYPE TEXT,
    MR_CONTENT      TEXT,
    MR_IP           TEXT,
    MR_CREATE_BY    TEXT,
    MR_CREATE_TIME  TEXT,
    MR_UPDATE_BY    TEXT,
    MR_UPDATE_TIME  TEXT,
    MR_IS_DELETED   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_BOOK (
    MR_ID          TEXT PRIMARY KEY,
    MR_USER_ID     TEXT,
    MR_BOOK_NAME   TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_MONTH_RECORD (
    MR_ID              TEXT PRIMARY KEY,
    MR_USER_ID         TEXT,
    MR_BOOK_ID         TEXT,
    MR_YEAR            INTEGER,
    MR_MONTH           INTEGER,
    MR_TOTAL_ASSET     TEXT,
    MR_TOTAL_LIABILITY TEXT,
    MR_NET_ASSET       TEXT,
    MR_MONTH_ON_MONTH  TEXT,
    MR_YEAR_ON_YEAR    TEXT,
    MR_NOTE            TEXT,
    MR_CREATE_BY       TEXT,
    MR_CREATE_TIME     TEXT,
    MR_UPDATE_BY       TEXT,
    MR_UPDATE_TIME     TEXT,
    MR_IS_DELETED      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_MONTH_ITEM_RECORD (
    MR_ID               TEXT PRIMARY KEY,
    MR_YEAR             INTEGER,
    MR_MONTH            INTEGER,
    MR_BOOK_ID          TEXT,
    MR_TEMPLATE_ITEM_ID TEXT,
    MR_ITEM_VALUE       TEXT,
    MR_CREATE_BY        TEXT,
    MR_CREATE_TIME      TEXT,
    MR_UPDATE_BY        TEXT,
    MR_UPDATE_TIME      TEXT,
    MR_IS_DELETED       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SYS_BACKUP_TEMPLATE_ITEM (
    MR_ID          TEXT PRIMARY KEY,
    MR_BOOK_ID     TEXT,
    MR_ITEM_NAME   TEXT,
    MR_ITEM_TYPE   INTEGER,
    MR_ICON        TEXT,
    MR_SORT        TEXT,
    MR_CREATE_BY   TEXT,
    MR_CREATE_TIME TEXT,
    MR_UPDATE_BY   TEXT,
    MR_UPDATE_TIME TEXT,
    MR_IS_DELETED  INTEGER DEFAULT 0
);

-- 初始化安全配置项（仅首次插入，已存在则跳过）
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-jwt-secret', 'mr.jwtSecret', '', 'JWT生成密钥，确定后不要修改，否则会导致所有登录失败', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-jwt-expire', 'mr.jwtExpire', '604800000', 'JWT过期时间，默认7天(毫秒)', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-reset-pwd', 'mr.resetPwdTokenSecret', '', '重置密码令牌生成密钥，确定后不要修改，否则会导致找回密码链接失效', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-activate', 'mr.activateTokenSecret', '', '账户激活令牌生成密钥，确定后不要修改，否则会导致激活链接失效', 0);

-- 初始化系统配置项
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-admin-mail', 'adminMail', '', '管理员邮箱【示例：admin@example.com】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-from', 'mail.from', '', '发送邮箱地址【示例：admin@example.com】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-hostname', 'mail.hostName', '', 'SMTP服务器【示例：admin@example.com】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-password', 'mail.password', '', '邮箱授权码', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-smtp-port', 'mail.smtpPort', '', 'SMTP服务器端口【示例：587】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-ssl', 'mail.ssl', '1', '是否开启SSL【示例：1或者0】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-ssl-smtp-port', 'mail.sslSmtpPort', '', 'SSL-SMTP服务器端口【示例：465】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-mail-username', 'mail.userName', '', '邮箱用户名【示例：admin@example.com】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-website', 'webSite', '', '站点地址【示例：https://mr.example.com/】', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-initialized', 'sys.initialized', '0', '系统是否已完成初始化（0-未初始化，1-已初始化）', 0);
INSERT OR IGNORE INTO SYS_CONFIG (MR_ID, MR_CONFIG_KEY, MR_CONFIG_VALUE, MR_REMARK, MR_IS_DELETED)
VALUES ('mr-conf-register-enabled', 'sys.registerEnabled', '0', '是否开启注册功能（0-关闭，1-开启）', 0);
