/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreementPopup: typeof import('./src/components/AgreementPopup.vue')['default']
    AuthLayout: typeof import('./src/components/AuthLayout.vue')['default']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendChart: typeof import('./src/components/TrendChart.vue')['default']
    VarActionSheet: typeof import('@varlet/ui')['_ActionSheetComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
}
