use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // FIN_BOOK
        manager
            .create_table(
                Table::create()
                    .table(FinBook::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(FinBook::MrId)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(FinBook::MrUserId).string().not_null())
                    .col(ColumnDef::new(FinBook::MrBookName).string().not_null())
                    .col(ColumnDef::new(FinBook::MrCreateBy).string())
                    .col(
                        ColumnDef::new(FinBook::MrCreateTime)
                            .date_time()
                            .not_null()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp)),
                    )
                    .col(ColumnDef::new(FinBook::MrUpdateBy).string())
                    .col(ColumnDef::new(FinBook::MrUpdateTime).date_time())
                    .col(
                        ColumnDef::new(FinBook::MrIsDeleted)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        // FIN_TEMPLATE_ITEM
        manager
            .create_table(
                Table::create()
                    .table(FinTemplateItem::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(FinTemplateItem::MrId)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(FinTemplateItem::MrBookId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinTemplateItem::MrItemName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinTemplateItem::MrItemType)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(FinTemplateItem::MrIcon).string().not_null())
                    .col(ColumnDef::new(FinTemplateItem::MrSort).string().not_null())
                    .col(ColumnDef::new(FinTemplateItem::MrCreateBy).string())
                    .col(
                        ColumnDef::new(FinTemplateItem::MrCreateTime)
                            .date_time()
                            .not_null()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp)),
                    )
                    .col(ColumnDef::new(FinTemplateItem::MrUpdateBy).string())
                    .col(ColumnDef::new(FinTemplateItem::MrUpdateTime).date_time())
                    .col(
                        ColumnDef::new(FinTemplateItem::MrIsDeleted)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        // FIN_MONTH_RECORD
        manager
            .create_table(
                Table::create()
                    .table(FinMonthRecord::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(FinMonthRecord::MrId)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(FinMonthRecord::MrUserId).string().not_null())
                    .col(ColumnDef::new(FinMonthRecord::MrBookId).string().not_null())
                    .col(ColumnDef::new(FinMonthRecord::MrYear).integer().not_null())
                    .col(ColumnDef::new(FinMonthRecord::MrMonth).integer().not_null())
                    .col(
                        ColumnDef::new(FinMonthRecord::MrTotalAsset)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthRecord::MrTotalLiability)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthRecord::MrNetAsset)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthRecord::MrMonthOnMonth)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthRecord::MrYearOnYear)
                            .double()
                            .not_null(),
                    )
                    .col(ColumnDef::new(FinMonthRecord::MrNote).string())
                    .col(ColumnDef::new(FinMonthRecord::MrCreateBy).string())
                    .col(
                        ColumnDef::new(FinMonthRecord::MrCreateTime)
                            .date_time()
                            .not_null()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp)),
                    )
                    .col(ColumnDef::new(FinMonthRecord::MrUpdateBy).string())
                    .col(ColumnDef::new(FinMonthRecord::MrUpdateTime).date_time())
                    .col(
                        ColumnDef::new(FinMonthRecord::MrIsDeleted)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        // FIN_MONTH_ITEM_RECORD
        manager
            .create_table(
                Table::create()
                    .table(FinMonthItemRecord::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrId)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrYear)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrMonth)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrBookId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrTemplateItemId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrItemValue)
                            .double()
                            .not_null(),
                    )
                    .col(ColumnDef::new(FinMonthItemRecord::MrCreateBy).string())
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrCreateTime)
                            .date_time()
                            .not_null()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp)),
                    )
                    .col(ColumnDef::new(FinMonthItemRecord::MrUpdateBy).string())
                    .col(ColumnDef::new(FinMonthItemRecord::MrUpdateTime).date_time())
                    .col(
                        ColumnDef::new(FinMonthItemRecord::MrIsDeleted)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(FinMonthItemRecord::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(FinMonthRecord::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(FinTemplateItem::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(FinBook::Table).to_owned())
            .await
    }
}

#[derive(Iden)]
enum FinBook {
    Table,
    MrId,
    MrUserId,
    MrBookName,
    MrCreateBy,
    MrCreateTime,
    MrUpdateBy,
    MrUpdateTime,
    MrIsDeleted,
}

#[derive(Iden)]
enum FinTemplateItem {
    Table,
    MrId,
    MrBookId,
    MrItemName,
    MrItemType,
    MrIcon,
    MrSort,
    MrCreateBy,
    MrCreateTime,
    MrUpdateBy,
    MrUpdateTime,
    MrIsDeleted,
}

#[derive(Iden)]
enum FinMonthRecord {
    Table,
    MrId,
    MrUserId,
    MrBookId,
    MrYear,
    MrMonth,
    MrTotalAsset,
    MrTotalLiability,
    MrNetAsset,
    MrMonthOnMonth,
    MrYearOnYear,
    MrNote,
    MrCreateBy,
    MrCreateTime,
    MrUpdateBy,
    MrUpdateTime,
    MrIsDeleted,
}

#[derive(Iden)]
enum FinMonthItemRecord {
    Table,
    MrId,
    MrYear,
    MrMonth,
    MrBookId,
    MrTemplateItemId,
    MrItemValue,
    MrCreateBy,
    MrCreateTime,
    MrUpdateBy,
    MrUpdateTime,
    MrIsDeleted,
}
